### ISSUE TITLE
Docker Couch dev

### ISSUE THREAD

**Issue by ikusteu** [librocco/librocco#134]
Using test data from baked in stores is fine, but we should add the logic to use a CouchDB instance with full store (of already generated test data baked in) and provide an
MVP way of stores (middle layer) communicating with the CouchDB instance (using PouchDB, if not full RxDB)

The focus of this is still hooking the data for interaction with the frontend and the best, most optimised solution for the data model doesn't need to be implemented here. We could even use one of the existing datamodel implementations as a first pass.

## Tasks

- [x] Provide the full test data transformed to have the fields necessary for frontend interaction (through stores layer)
- [x] Create CouchDB container filled with said test data (and deploy on GitHub container repo)
- [x] Create a minimal PouchDB interface (or use an existing one from `datamodel-tests`)
- [x] Create an "offline" option fallback:
  - we should be able to use the stores (for frontend purposes) without the CouchDB contianer
  - in that case the existing data, committed in `/apps/web-client/src/lib/data` would be used
  - we should be able to get the same functionality in that case (that's what the middle layer is here for)
