### ISSUE TITLE
Feature: book actions

### ISSUE THREAD

**Issue by ikusteu** [librocco/librocco#158]
# Book actions on db interface

I wanted to keep it simple as a first pass. If needed, we can re-iterate later (maybe implement views/streams).

## Requirements

- `db.getBooks()` - should accept an array of isbns and return an array of `CouchDocument<BookEntry>`
- `db.getBook()` - see `db.getBooks()` (should return `undefined` if book doesn't exist)
- `db.upsertBook()` 
  - should accept a `BookEntry` and set (if it doesn't exist), or update 
  - I imagine it could pull the data first (get `_rev` string and update
  - later we can, maybe, implement the functionality so that the book is fetched immediately (when typing an isbn), with the rev number and existing data **(this is an enhancement)**

## Tasks

- [x] Update the `DatabaseInterface` declaration to reflect the requirements
- [x] create `db.getBooks()`
- [x] create `db.getBook()`
- [x] create `db.upsertBook()`
- [x] in `apps/web-client` update the stores to use the db interface to receive the book data (instead of hardcoded store, as is the current implementation) - delete the dev books store afterwards

## Possible enhancements

- When scanning/typing in the isbn, the the `getBook` could be performed to automatically populate the form data (and include `_rev` string for update) - this isn't too closely related to this ticket per se, but it touches on the functionality
