### ISSUE TITLE
Enhancement: Book actions 2nd pass

### ISSUE THREAD

**Issue by ikusteu** [librocco/librocco#168]
The book actions (`getBook`, `getBooks`, `upsertBook`) are currently methods on the `db` interface. It would be slightly tidier to create a `db.books` method, returning a new class `Books`. That class should then have `.upsert` and `.get` methods, as well as a new `stream` method.

## Tasks

- [x] Create an `interface` for `Books` (in db/src/types.ts):
  - `get` accepts an array of isbns and returns `BookEntry` or `undefined` (in place of the old `db.getBooks`)
  - `upsert` accepts an array of `BookEntry` and does an equivalent of `db.upsertBook` on each of them
  - `stream()` accepts an array of isbns and behaves like `get` only with live updates

- [x] Update `DatabaseInterface` type:
  - remove book actions
  - add `.books` (returning a `Books` interface)

### In implementations/version1.1:

- [x] Create the `Books` class implementing the `Books` interface
- [x] Remove book actions from `Database` class

### Test the interface (in `db` package)

- [x] We can test updates, get and streams in the same test
