### ISSUE TITLE
Hook up the functionality from UI to the db

### ISSUE THREAD

**Issue by ikusteu** [librocco/librocco#205]
I'm opening up this ticket more as a checklist for app integration. As @delasous mentioned, we should work towards hooking up the entire app with the "backend" (db interface), which would allow us to see all of the parts in action and pinpoint some additional features necessary (in the UI, or db interface), if any.

_Note: while writing this, I might have oversimplified some of the functionality, but the goal is to have it working the full round trip (add, delete, update, books, notes, etc...) and then extend with some eye/UX candy + additional features. One of additional features is definitely the search, which I've omitted all functionality and support for it in these tasks as I believe it should be handled in the next pass._

### TODO:

- [x] we should be able to add now books to a note:
  - the simplest solution I see here is to add the 'Scan to add books...' text input, have it accept (for now only user typed in) isbn and, on 'Create' button click run `note.addVolumes({ isbn, quantity: 1 })`:
     -  `isbn` would be the one provided to the input
     -  `quantity: 1` (as it could be specifically set on the transaction row, more below :point_down: )
     - `warehouseId` omitted as, that way, the db will automatically fall back to parent warehouse id (for inbound notes) or `""` for outbound notes (letting the user select the warehouse on transaction row more below 👇 
  - I understand that 'Create' button might have a different use case when the functionality is fully integrated (open up a create book dialog, allowing user to input the book data for the book), but for simplicity's sake, I think we can use it in this way now and then, later on, add an additional step (checking if book should be created or so)

- [ ] we should be able to update the volume transaction on the note:
  - this goes for both transaction `quantity` (as mentioned above) as well as `warehouseId` (in case of outbound notes)
  - `note.updateTransaction` can be used for both updates
  - my suggestion for quantity update is to toggle between quantity badge and input element for quantity (and maybe provide a submit button, used to update the quantity) 
  - outbound note -> warehouse selection -> available warehouses - I think, as a first pass, we can simply have all the warehouses as 'available'...as a further enhancement:
    - the transaction, added on outbound note, would use `warehouseId` of the only outbound warehouse that book is available in (if there's only one available warehouse for the book)
    - if there are multiple warehouses (or none) where the book is available, it should fall back to `""`
  - we can live without the aforementioned enhancements for now, as user won't be able to commit the note in case of any kind of incompatible `warehouseId`, moreover, the same functionality used to verify the transactions when committing (already in place in the db interface) can be extended to stream book availability in warehouses and used to achieve said enhancements (default fallback/available warehouse list)

- [ ] we should be able to remove transaction rows from the note:
  - in the simplest form, this would require adding `onDeleteRows` (or something like that) to the `InventoryTable` component and have it run `note.removeTransactions` for specified rows, whereas the table itself would be updated by db update (direct addition/removal to/from the table can be added as a second pass, but I don't see it being overly complicated either)

- [ ] we should signal why a particular note can't be committed:
  - we have db guards in place for this, throwing a serialised error with info about invalid transaction rows, blocking the commit, so we should use those to show a notification and/or highlight the invalid rows
