### ISSUE TITLE
Feature: enhance single remote config / ux

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#238]
- There are a few options for replication: `to`, `from`, `bi-directional "sync"`, but to get started I don’t think we should handle all of these, and I think we should only handle a single “default” replication config. Meaning:
    1. Bi-directional sync
    2. Live sync with either `retry = false` OR `retry = true`
        1. Note: I was initially leaning towards default being retry = false, but by the time I got to the end of these notes, I was open to the alternative as I think it can make for a richer reporting of a remote’s “status”. 
            1. To do so: we would have to update so that the network error thrown in `.on("error")` is used to update the status, rather than cancelling the replication handler
    - This means that:
        - for “one time” replication ⇒ a user will have to let live run until it is complete, then cancel it.
        - instead of “auto retry” ⇒ a user needs to explicitly re-start replication from settings screen
- Config / UX:
    - A user should enter a new remote URL and save it. Once it is saved, replication should start.
    - The URL should not be open for editing once it is set. Editing the URL means interrupting (stopping) the replication and starting it again on save
    - Replication events / status of the remote connection should be communicated to the user:
        - Via:
            1. Toasts that notify the user of important changes as they happen
            2. Badges / controls next to remote settings to notify the user of the current state of the connection and actions they can perform to affect it.
        - Status should stick close to Pouch api:
            1. “Synced” - Live replication is UTD, waiting for more changes…
                1. `.on("pause", (err) => {})` err will indicate UTD if `live | retry: true`, or if “one time” it will be notified in `.on("complete", (info) => {}`
                2. `.on("active", () => {})` will fire after “pause”, either after new changes have happened, or user is back online. Could be used to reset to “In progress”
            2. “In progress” - Currently doing its thing…
                1. `.on("change", (info) => {})` info indicates progress
                2. This can be upgraded to progress bar as an enhancement. Progress bar could also be held in suspended toast
            3. “Error” - There was a problem…
                1. From docs: “If `retry` is `false`, this will also fire when the user goes offline or another network error occurs (so you can handle retries yourself, if you want)” ⇒ It should be cancelled and re-started.
                2. If we are defaulting replication settings to `retry: false` , we could also add “Offline” - User is offline, waiting to reconnect…
                    1. `.on("pause", (err) => {})` err indicates disconnected 
    - Couch replication UI also communicates “Start Time” - is this useful to communicate here?
    - Actions - a user should be able to:
        - Cancel replication
        - Retry replication.
- Replication shouldn’t happen in `load` or `onMount`:
    1. This falls apart quickly when we have multiple remotes all of which can be in different states: a remote could be added-started, stopped, or restarted - all of which should be managed independantly from the apps general loading state.
    2. Note: in dev, the remote is currently set on load which triggers replication automatically. This should probably continue to happen, so devs don’t have to set it themselves everytime they spin up the app, but how this will be achieved needs to change.

**Comment by delasous** [comment]
### Tasks
- [ ] Update `db/replicator.ts`:
    1. Remove "live" method
    2. Reduce "to", "from" and "sync" methods into a single "replicate" method
        1. Expand args, `ctx`, `url` and:
            1. `direction` - defines direction of replication: "to", "from", "sync"
            2. `options` - forwards pouchDB replicate options: "live", "retry"... + advanced config
            
- [ ] Build UI - remote config controls:
    1. Configuration should be one-way - that is: once controls have accepted input and config is saved, UI should show `remote url`, `replication status` as non-interactive elements, and buttons to `edit` or `cancel`. Either action will cancel replication, except the latter will completely clear the config.
    2. Controls:
        1. Input for remote url
        2. Additional config (hidden in collapsed `details` element) and set to defaults:
            1. `direction` select: "to", "from", "sync". Default = "sync"
            2. `live` toggle. Default = "true"
            4. `retry` toggle. Default = "true". Disables when `live` is false
        3. "save" button to save config and init replication
            
 - [ ] Build replication store:
    1. Add store that manages a single remote - its config, status and handlers:
        1. `config`: url, direction, replication options
        2. `handler`: reference to replication handler:  to subscribe to event & `cancel` methods
        3. `status`: describes remote state translated from replication events:
            1. ACTIVE - connected to remote and replicating. `progress` will be defined
            2. ERROR - unrecoverable error. `info` will defined error message
            6. LIVE - `live` and connected to remote, awaiting changes
            7. COMPLETE - not `live`, replication with remote has finished
            8. INACTIVE - awaiting config
        4. `progress`: if `status: ACTIVE`, will describe % completion based off of "change events", otherwise null
        5. `info`: additional status details/messages passed from event handlers, e.g error message, "paused event" message (any of: waiting for changes, & if `retry: true` - connection lost)
        9. `init()`: sets config & starts replication
        10. `cancel()`: cancels replication and clears config
        11. `edit()`: cancels replication
    2. Remove replication logic from `inventory/+layout.svelte`
    3. Add replication UI to `settings/+page.svelte`, and connect `init()` to "save"

- [ ] Add & extend toasts to communicate replication events:
    1. Changes in replication status should trigger timed-out/dismissable toasts
    2. Replication progress should be communicated via progress bar in non-dismimssable. This is currently not possible: extend toast implementation / define separate `progress` toast component ...
