### ISSUE TITLE
Extend db api to support plugins

### ISSUE THREAD

**Issue by ikusteu** [librocco/librocco#339]
As described in #323 
This unit of work should tackle the first pass:
- create `.plugin` method on the db interface
- the `.plugin` method should return an interface satisfying the interface of the plugin at hand (e.g. `book-fetcher` plugin) + `.register` method
- the initial response to `.plugin("book-fetcher")` (for instance) should return a fallback satisfying `BookFetcherPlugin` interface and with noop methods (and the aforementioned `.register` method)
- calling `.register` on a plugin and passing a different plugin instance should wrap the instance with the `.register` method and register the plugin so that all subsequent calls to the same plugin (e.g. `.plugin("book-fetcher")`) would return the registered instance

### Tasks
- [x] Create the `.plugin` api
- [x] Create the `BookFetcherPlugin` fallback
- [x] Create and test the registering logic
