### ISSUE TITLE
Feature: TypographyEditable

### ISSUE THREAD

**Issue by ikusteu** [librocco/librocco#64]
## Component: TypographyEditable

**Description:** A wrapper around typography providing wysiwyg functionality.

**Mockup:** No mockup per se (@delasous maybe you can just create one typography variant with the editable pencil button in the mockup)

### Requirements:

It would really make sense to store this next to the `Typography`, i.e. `pkg/ui/components/Typography` and export it as a named export from `Typography/index.ts`.

#### Props:
- see #62 props 
- **onSave** (optional: Function): 
  - should handle the updating functionality 

#### Storybook (stories):
- Default: 
  - showing the aforementioned typography with the pencil button (no need for all the variants as those will have been covered in #62 stories)

#### Functionality (should be tested):
- Updating itself
  - should update itself on save when the string is edited
  - should update itself on props change (if the update comes from outside the component)
-  Lifting updates
  - should lift updates, after editing, using the `onSave` function provided through props
  - should submit updates on return key press

### Possible enhancements:
- null

### Progress:

Depends on #62 and #63 

**TODO:**

- [ ] Implement styles (the edit pencil)
- [ ] Develop and test functionality
- [ ] Create storybook preview

**Comment by delasous** [comment]
Added in #139
